package org.mio.progettoingsoft.advCards.sealed;

public enum CardState {
    CREW_REMOVE_CHOICE, ENGINE_CHOICE, DRILL_CHOICE, ACCEPTATION_CHOICE, COMPARING, FINALIZED, GOODS_PLACEMENT, APPLYING, IDLE
}
